### ISSUE TITLE
ArrayIndexOutOfBoundsException when multithreading call 

### ISSUE THREAD

**Issue by thangdc94** [vncorenlp/VnCoreNLP#20]
When I submit multiple requests async to VnCoreNLPServer I got ArrayIndexOutOfBoundsException: -1

```
2019-11-05 15:39:37,233 [qtp950350040-18] ERROR vncorenlp.VnCoreNLPServer.handle(VnCoreNLPServer.java:278) - -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at marmot.util.Encoder.append(Encoder.java:68)
	at marmot.morph.MorphWeightVector.extractStateFeatures(MorphWeightVector.java:366)
	at marmot.core.SimpleTagger.getStates(SimpleTagger.java:181)
	at marmot.core.SimpleTagger.getSumLattice(SimpleTagger.java:322)
	at marmot.core.SimpleTagger.tag_states(SimpleTagger.java:565)
	at marmot.morph.MorphTagger.tagWithLemma(MorphTagger.java:49)
	at vn.corenlp.postagger.PosTagger.tagSentence(PosTagger.java:52)
	at vn.pipeline.Sentence.createWords(Sentence.java:60)
	at vn.pipeline.Sentence.init(Sentence.java:53)
	at vn.pipeline.Sentence.<init>(Sentence.java:30)
	at vncorenlp.VnCoreNLPServer.annotate(VnCoreNLPServer.java:236)
	at vncorenlp.VnCoreNLPServer.handle(VnCoreNLPServer.java:269)
	at vncorenlp.VnCoreNLPServer.lambda$main$2(VnCoreNLPServer.java:178)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1671)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vncorenlp** [comment]
It would be better to post your issue here: https://github.com/dnanhkhoa/python-vncorenlp
