### ISSUE TITLE
Cannot start NER and PARSE service

### ISSUE THREAD

**Issue by CaoHoangTung** [vncorenlp/VnCoreNLP#31]
After cloning the repo, I tried to run `vncorenlp -Xmx2g <FULL-PATH-to-VnCoreNLP-jar-file> -p 9000 -a "wseg,pos,ner,parse"` and it gave me the following error

`
2020-06-30 22.26.18 INFO VnCoreNLPServer - Using annotators: wseg, pos, ner, parse
2020-06-30 22:26:18 INFO  WordSegmenter:24 - Loading Word Segmentation model
2020-06-30 22:26:18 INFO  PosTagger:21 - Loading POS Tagging model
2020-06-30 22:26:21 INFO  NerRecognizer:33 - Loading NER model
2020-06-30 22.26.21 INFO GlobalLexica - Loading word clusters
2020-06-30 22.26.21 ERROR VnCoreNLPServer - null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at vncorenlp.VnCoreNLPServer.loadVnCoreNLP(VnCoreNLPServer.java:91)
        at vncorenlp.VnCoreNLPServer.main(VnCoreNLPServer.java:175)
Caused by: java.lang.ExceptionInInitializerError
        at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
        at java.nio.file.Paths.get(Paths.java:84)
        at edu.emory.mathcs.nlp.common.util.IOUtils.createArtifactInputStream(IOUtils.java:363)
        at edu.emory.mathcs.nlp.common.util.IOUtils.createArtifactObjectInputStream(IOUtils.java:396)
        at edu.emory.mathcs.nlp.component.template.lexicon.GlobalLexica.getGlobalLexicon(GlobalLexica.java:95)
        at edu.emory.mathcs.nlp.component.template.lexicon.GlobalLexica.getGlobalLexicon(GlobalLexica.java:80)
        at edu.emory.mathcs.nlp.component.template.lexicon.GlobalLexica.<init>(GlobalLexica.java:72)
        at vn.pipeline.LexicalInitializer.initializeLexica(LexicalInitializer.java:74)
        at vn.pipeline.LexicalInitializer.initialize(LexicalInitializer.java:44)
        at vn.corenlp.ner.NerRecognizer.<init>(NerRecognizer.java:39)
        at vn.corenlp.ner.NerRecognizer.initialize(NerRecognizer.java:26)
        ... 6 more
Caused by: java.lang.RuntimeException: default directory must be absolute
        at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:54)
        at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
        at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
        at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
        at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
        at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
        at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:63)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
        at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
        at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:96)
        at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
        ... 17 more
`

Howerver, running the service with only **"wseg,pos"** worked as expected

Here is my Java version

`
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
`

**Comment by datquocnguyen** [comment]
I had no idea what happened. 
Please recompile the .jar vncorenlp file with `mvn clean` and then `mvn install`

**Comment by CaoHoangTung** [comment]
It appeared to be an out-of-memory issue (not related to the code) :) I've managed to fix it.

**Comment by datquocnguyen** [comment]
@CaoHoangTung Please could you provide some more details how you did fix the problem? 
Other users might avoid the similar issue. Thanks!

**Comment by CaoHoangTung** [comment]
As I've mentioned earlier, the issue is related to lack of memory. The machine I was running on has too little RAM available, which caused the problem. At the moment I can't remember exactly what I'd done to resolve the issue, but try to change the flag -Xmx2g to something bigger like -Xmx5g, and make sure the device is capabled :-)

**Comment by datquocnguyen** [comment]
Please use the new wrapper: https://github.com/thelinhbkhn2014/VnCoreNLP_Wrapper

**Comment by 51001624** [comment]
anh ơi, em cũng bị lỗi này !
